### ISSUE TITLE
About training dataset

### ISSUE THREAD

**Issue by xurong1981** [huangzehao/torch-srgan#3]
For training, you wrote "Download imagenet valset for training", I am not sure which one in imagenet is that you pointed out by "imagenet valset" ? Because I found there were much datasets in imagenet.

**Comment by xurong1981** [comment]
For example, which one should I use by this link "http://image-net.org/download-images" ? Or could you please give a link for downloading imagenet valset for training ?

**Comment by huangzehao** [comment]
Hi, the training datasets I used is  Validation images (all tasks). 6.3GB. MD5: 29b22e2961454d5413ddabcf34fc5622 in http://www.image-net.org/challenges/LSVRC/2012/nonpub-downloads.

**Comment by xurong1981** [comment]
I see. Thank you so much for your quick reply. I will make a try.
